# Generated by Django 4.2.7 on 2023-11-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
