# Generated by Django 4.2.7 on 2023-11-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIMS', '0002_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='access_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
